### ISSUE TITLE
`jsonnet: Evaluate File` does not work in Windows

### ISSUE THREAD

**Issue by csj8520** [grafana/vscode-jsonnet#19]
An error occurred executing the `jsonnet: Evaluate File` command in Windows.

![image](https://user-images.githubusercontent.com/39072685/193185526-54b6a0a6-ae44-4609-b1c1-0cf2a6c15f98.png)

**Comment by cazeaux** [comment]
Hello

I have the same issue. I can't figure out where the error is.

**Comment by julienduchesne** [comment]
I published a tentative fix in v0.3.2. Let me know if it works!

**Comment by csj8520** [comment]
@julienduchesne 

Thank you, but it still doesn't work, I test the following modification can work properly

![image](https://user-images.githubusercontent.com/39072685/196319633-b14ca742-b496-4900-98c1-d74a99a2572e.png)

**Comment by julienduchesne** [comment]
Thanks for the tip @csj8520. I only have linux and mac to test 😅. I've released v0.3.3, let me know if it works!

**Comment by csj8520** [comment]
@julienduchesne 
Thank you for your help. It can be used normally now

**Comment by cazeaux** [comment]
Thank you @julienduchesne, this is working fine now
